import { Course } from "./types";

export const coursesData: Course[] = [
  {
    slug: "jee-dropper",
    title: "IIT JEE Dropper",
    description: "JEE dropper course for 12th pass students",
    longDescription: `This is a highly intensive course designed for JEE aspirants who have completed Class 12 and are targeting JEE Main and Advanced in the upcoming year. This batch offers rigorous practice, test series, personal mentoring and doubt sessions to boost your rank.`,
    image: "/course/iitdropper.png",
    targetExam: "JEE",
    programType: "Dropper",
    price: "75,000/-",
    discountedPrice: "60,000/-",
  },
  {
    slug: "jee-one-year",
    title: "IIT JEE One Year",
    description: "One year course for JEE aspirants in Class 12",
    longDescription: `Many of IIT-JEE aspirants do feel at the far end of their preparation that they want to quickly revise the entire syllabus at least once or twice to make them feel more confident and better equipped to face the daunting task of facing the challenge of IIT-JEE few weeks later. The ESP is a meticulous collection of 1500 assorted problems (500 each in Physics, Chemistry and Mathematics). These problems cover the complete IIT-JEE syllabus of respective subject through various concepts and variety of problems. Course Structure: In Express, the expert Faculty Team of Arpitas shall discuss the problems in the Classroom within a period of five weeks. The Classrooms will be as much interactive as possible to make the students learn and quickly revise the entire IIT-JEE syllabus with high level of conceptual understanding and grasping of fundamentals.

Through Express; the aspirants for IIT-JEE shall get an exposure to Resonance’s Teaching Methodology (Power of Classroom Teaching) and experience the expertise of its Research & Development Team (Quality & Conceptual Problems) in terms of quick yet effective course revision with improved confidence and motivation level.`,
    image: "/images/courses/jee-one-year.jpg",
    targetExam: "JEE",
    programType: "One Year",
    price: "75,000/-",
    discountedPrice: "60,000/-",
  },
  {
    slug: "jee-two-year",
    title: "IIT JEE Two Year",
    description: "Two year course for JEE aspirants in Class 11",
    longDescription: `Arpitas Academy (ASA) : Your unwavering support on the path to medical & Engineering excellence. Arpitas Academy (ASA) is on of gthe most Trusted JEE/ NEET coaching in Pune, providing offline coaching to to Engineering and medical aspirants. We not only prepare for the exam but also empower them to succeed in their careers. Their goal is to equip individuals with the knowledge, confidence, and determination to achieve their aspiration and gain admissions to Dream colleges. “Don't just hope for success; choose Arpitas Academy (ASA) and make it a reality” Don't leave your dreams to chance. Join Arpitas Academy (ASA) today and embark on your path to success. We'll be your compass, your cheerleader, and your partner in this thrilling conquest. Are you ready to ignite your brilliance? Arpitas Academy (ASA)—the best JEE/NEET/CET oaching in vecinity

Here's how Arpitas Academy (ASA) sets you apart: Expert Faculty: Our JEE/NEET coaching institute boasts a team of highly qualified and experienced teachers who have a deep understanding of how to teach the syllabus in live online and offline modes, so it offers the best online coaching for NEET and the best online coaching for NEET in Pune. that guides you with an unwavering commitment to your success. They possess a wealth of knowledge and a passion for teaching, ensuring you receive top-notch medical preparation. NEET UG Study Material Designed for Excellence: Our best coaching for NEET UG comprehensive study materials are meticulously crafted by our expert faculty based on in-depth research and the latest exam patterns. They simplify complex concepts, making them easy to understand and retain. We update our study materials and teaching methods annually to keep pace with the changing exam patterns and ensure you're always ahead of the curve. Performance Analysis and Self-Improvement by Mock Tests: Our best NEET coaching in city. Institutes provides well-structured assessments and mock tests to evaluate your progress. Regular tests and mock exams mimic the actual exam format, equipping you with the necessary practice and confidence. We provide detailed reports from periodic tests, highlighting your strengths and weaknesses. This self-assessment empowers you to strategize, improve, and maximise your performance. Personalized Guidance and Doubt Clearance of Aspirants: We believe in individualised attention. Our unique "I-NEED", offer students the opportunity to have their questions answered personally by faculty, ensuring no one falls behind. Year-Round Support and Motivation: As part of Arpitas Academy (ASA), you become part of a vibrant community of like-minded individuals. We encourage and motivate each other to make the most of our abilities, creating a positive and supportive environment that propels you towards success. At Arpitas Academy (ASA), success isn't just about results; it's about empowering you to conquer your dreams with confidence and a strong foundation. Join us and witness the difference:`,
    image: "/images/courses/jee-two-year.jpg",
    targetExam: "JEE",
    programType: "Two Year",
    price: "1,20,000/-",
    discountedPrice: "1,00,000/-",
  },
  {
    slug: "neet-dropper-batch",
    title: "NEET Dropper Batch",
    description: "NEET dropper course for 12th pass students",
    longDescription: `An intensive NEET preparation course for students who have completed Class 12. Includes exhaustive practice, test series, and doubt-solving sessions to maximize your NEET score.`,
    image: "/course/neet1.png",
    targetExam: "NEET",
    programType: "Dropper",
    price: "75,000/-",
    discountedPrice: "60,000/-",
  },
  {
    slug: "neet-one-year",
    title: "NEET One Year",
    description: "One year course for NEET aspirants in Class 12",
    longDescription: `A one-year program for Class 12 students targeting NEET. Comprehensive coverage of Physics, Chemistry, and Biology with regular assessments and expert mentoring.`,
    image: "/images/courses/neet-one-year.jpg",
    targetExam: "NEET",
    programType: "One Year",
    price: "75,000/-",
    discountedPrice: "60,000/-",
  },
  {
    slug: "neet-two-year",
    title: "NEET Two Year",
    description: "Two year course for NEET aspirants in Class 11",
    longDescription: `Arpitas Academy (ASA) : Your unwavering support on the path to medical & Engineering excellence. Arpitas Academy (ASA) is on of gthe most Trusted JEE/ NEET coaching in Pune, providing offline coaching to to Engineering and medical aspirants. We not only prepare for the exam but also empower them to succeed in their careers. Their goal is to equip individuals with the knowledge, confidence, and determination to achieve their aspiration and gain admissions to Dream colleges. “Don't just hope for success; choose Arpitas Academy (ASA) and make it a reality” Don't leave your dreams to chance. Join Arpitas Academy (ASA) today and embark on your path to success. We'll be your compass, your cheerleader, and your partner in this thrilling conquest. Are you ready to ignite your brilliance? Arpitas Academy (ASA)—the best JEE/NEET/CET oaching in vecinity

Here's how Arpitas Academy (ASA) sets you apart: Expert Faculty: Our JEE/NEET coaching institute boasts a team of highly qualified and experienced teachers who have a deep understanding of how to teach the syllabus in live online and offline modes, so it offers the best online coaching for NEET and the best online coaching for NEET in Pune. that guides you with an unwavering commitment to your success. They possess a wealth of knowledge and a passion for teaching, ensuring you receive top-notch medical preparation. NEET UG Study Material Designed for Excellence: Our best coaching for NEET UG comprehensive study materials are meticulously crafted by our expert faculty based on in-depth research and the latest exam patterns. They simplify complex concepts, making them easy to understand and retain. We update our study materials and teaching methods annually to keep pace with the changing exam patterns and ensure you're always ahead of the curve. Performance Analysis and Self-Improvement by Mock Tests: Our best NEET coaching in city. Institutes provides well-structured assessments and mock tests to evaluate your progress. Regular tests and mock exams mimic the actual exam format, equipping you with the necessary practice and confidence. We provide detailed reports from periodic tests, highlighting your strengths and weaknesses. This self-assessment empowers you to strategize, improve, and maximise your performance. Personalized Guidance and Doubt Clearance of Aspirants: We believe in individualised attention. Our unique "I-NEED", offer students the opportunity to have their questions answered personally by faculty, ensuring no one falls behind. Year-Round Support and Motivation: As part of Arpitas Academy (ASA), you become part of a vibrant community of like-minded individuals. We encourage and motivate each other to make the most of our abilities, creating a positive and supportive environment that propels you towards success. At Arpitas Academy (ASA), success isn't just about results; it's about empowering you to conquer your dreams with confidence and a strong foundation. Join us and witness the difference:`,
    image: "/images/courses/neet-two-year.jpg",
    targetExam: "NEET",
    programType: "Two Year",
    price: "1,20,000/-",
    discountedPrice: "1,00,000/-",
  },
  {
    slug: "cet-dropper",
    title: "CET Dropper",
    description: "CET dropper course for 12th pass students",
    longDescription: `A dedicated course for CET aspirants who have completed Class 12. Includes rigorous practice, mock tests, and personalized mentoring for best results.`,
    image: "/images/courses/cet-dropper.jpg",
    targetExam: "CET",
    programType: "Dropper",
    price: "60,000/-",
    discountedPrice: "50,000/-",
  },
  {
    slug: "cet-one-year",
    title: "CET One Year",
    description: "One year course for CET aspirants in Class 12",
    longDescription: `A one-year program for Class 12 students preparing for CET. Covers all subjects with regular tests and expert guidance.`,
    image: "/images/courses/cet-one-year.jpg",
    targetExam: "CET",
    programType: "One Year",
    price: "60,000/-",
    discountedPrice: "50,000/-",
  },
  {
    slug: "cet-two-year",
    title: "CET Two Year",
    description: "Two year course for CET aspirants in Class 11",
    longDescription: `Arpitas Academy (ASA) : Your unwavering support on the path to medical & Engineering excellence. Arpitas Academy (ASA) is on of gthe most Trusted JEE/ NEET coaching in Pune, providing offline coaching to to Engineering and medical aspirants. We not only prepare for the exam but also empower them to succeed in their careers. Their goal is to equip individuals with the knowledge, confidence, and determination to achieve their aspiration and gain admissions to Dream colleges. “Don't just hope for success; choose Arpitas Academy (ASA) and make it a reality” Don't leave your dreams to chance. Join Arpitas Academy (ASA) today and embark on your path to success. We'll be your compass, your cheerleader, and your partner in this thrilling conquest. Are you ready to ignite your brilliance? Arpitas Academy (ASA)—the best JEE/NEET/CET oaching in vecinity

Here's how Arpitas Academy (ASA) sets you apart: Expert Faculty: Our JEE/NEET coaching institute boasts a team of highly qualified and experienced teachers who have a deep understanding of how to teach the syllabus in live online and offline modes, so it offers the best online coaching for NEET and the best online coaching for NEET in Pune. that guides you with an unwavering commitment to your success. They possess a wealth of knowledge and a passion for teaching, ensuring you receive top-notch medical preparation. NEET UG Study Material Designed for Excellence: Our best coaching for NEET UG comprehensive study materials are meticulously crafted by our expert faculty based on in-depth research and the latest exam patterns. They simplify complex concepts, making them easy to understand and retain. We update our study materials and teaching methods annually to keep pace with the changing exam patterns and ensure you're always ahead of the curve. Performance Analysis and Self-Improvement by Mock Tests: Our best NEET coaching in city. Institutes provides well-structured assessments and mock tests to evaluate your progress. Regular tests and mock exams mimic the actual exam format, equipping you with the necessary practice and confidence. We provide detailed reports from periodic tests, highlighting your strengths and weaknesses. This self-assessment empowers you to strategize, improve, and maximise your performance. Personalized Guidance and Doubt Clearance of Aspirants: We believe in individualised attention. Our unique "I-NEED", offer students the opportunity to have their questions answered personally by faculty, ensuring no one falls behind. Year-Round Support and Motivation: As part of Arpitas Academy (ASA), you become part of a vibrant community of like-minded individuals. We encourage and motivate each other to make the most of our abilities, creating a positive and supportive environment that propels you towards success. At Arpitas Academy (ASA), success isn't just about results; it's about empowering you to conquer your dreams with confidence and a strong foundation. Join us and witness the difference:`,
    image: "/images/courses/cet-two-year.jpg",
    targetExam: "CET",
    programType: "Two Year",
    price: "1,00,000/-",
    discountedPrice: "85,000/-",
  },
  {
    slug: "nda-dropper",
    title: "NDA Dropper",
    description: "NDA dropper course for 12th pass students",
    longDescription: `An intensive NDA preparation course for students who have completed Class 12. Includes focused study plans, test series, and personal mentoring.`,
    image: "/images/courses/nda-dropper.jpg",
    targetExam: "NDA",
    programType: "Dropper",
    price: "50,000/-",
    discountedPrice: "40,000/-",
  },
  {
    slug: "nda-one-year",
    title: "NDA One Year",
    description: "One year course for NDA aspirants in Class 12",
    longDescription: `A one-year program for Class 12 students targeting NDA. Comprehensive coverage of all subjects, regular tests, and expert mentoring.`,
    image: "/images/courses/nda-one-year.jpg",
    targetExam: "NDA",
    programType: "One Year",
    price: "50,000/-",
    discountedPrice: "40,000/-",
  },
  {
    slug: "nda-two-year",
    title: "NDA Two Year",
    description: "Two year course for NDA aspirants in Class 11",
    longDescription: `A two-year integrated program for students entering Class 11, focusing on NDA preparation with in-depth teaching and regular assessments.`,
    image: "/images/courses/nda-two-year.jpg",
    targetExam: "NDA",
    programType: "Two Year",
    price: "85,000/-",
    discountedPrice: "70,000/-",
  },
  // Foundation courses (CBSE, ICSE, MH Board) already follow the structure
  // If you want to add price/discountedPrice for foundation courses, add them similarly:
  {
    slug: "foundation-cbse-7",
    title: "Foundation Class 7 CBSE",
    description: "Foundation course for Class 7 CBSE students",
    longDescription: `A foundation course for Class 7 CBSE students, focusing on building strong fundamentals in Science and Mathematics for future competitive exams.`,
    image: "/images/courses/foundation-cbse-7.jpg",
    targetExam: "Foundation",
    board: "CBSE",
    classLevel: "7",
    price: "20,000/-",
    discountedPrice: "15,000/-",
  },
  {
    slug: "foundation-cbse-8",
    title: "Foundation Class 8 CBSE",
    description: "Foundation course for Class 8 CBSE students",
    longDescription: `A foundation course for Class 8 CBSE students, focusing on strengthening concepts in Science and Mathematics to prepare for higher studies and competitive exams.`,
    image: "/images/courses/foundation-cbse-8.jpg",
    targetExam: "Foundation",
    board: "CBSE",
    classLevel: "8",
    price: "22,000/-",
    discountedPrice: "17,000/-",
  },
  {
    slug: "foundation-cbse-9",
    title: "Foundation Class 9 CBSE",
    description: "Foundation course for Class 9 CBSE students",
    longDescription: `A foundation course for Class 9 CBSE students, designed to build a strong base in Science and Mathematics for future competitive exams like JEE and NEET.`,
    image: "/images/courses/foundation-cbse-9.jpg",
    targetExam: "Foundation",
    board: "CBSE",
    classLevel: "9",
    price: "25,000/-",
    discountedPrice: "20,000/-",
  },
  {
    slug: "foundation-cbse-10",
    title: "Foundation Class 10 CBSE",
    description: "Foundation course for Class 10 CBSE students",
    longDescription: `A foundation course for Class 10 CBSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-cbse-10.jpg",
    targetExam: "Foundation",
    board: "CBSE",
    classLevel: "10",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-icse-10",
    title: "Foundation Class 10 ICSE",
    description: "Foundation course for Class 10 ICSE students",
    longDescription: `A foundation course for Class 10 ICSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-icse-10.jpg",
    targetExam: "Foundation",
    board: "ICSE",
    classLevel: "10",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-mh-10",
    title: "Foundation Class 10 MH Board",
    description: "Foundation course for Class 10 MH Board students",
    longDescription: `A foundation course for Class 10 MH Board students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-mh-10.jpg",
    targetExam: "Foundation",
    board: "MH Board",
    classLevel: "10",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-cbse-11",
    title: "Foundation Class 11 CBSE",
    description: "Foundation course for Class 11 CBSE students",
    longDescription: `A foundation course for Class 11 CBSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-cbse-11.jpg",
    targetExam: "Foundation",
    board: "CBSE",
    classLevel: "11",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-cbse-12",
    title: "Foundation Class 12 CBSE",
    description: "Foundation course for Class 12 CBSE students",
    longDescription: `A foundation course for Class 12 CBSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-cbse-12.jpg",
    targetExam: "Foundation",
    board: "CBSE",
    classLevel: "12",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-icse-11",
    title: "Foundation Class 11 ICSE",
    description: "Foundation course for Class 11 ICSE students",
    longDescription: `A foundation course for Class 11 ICSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-icse-10.jpg",
    targetExam: "Foundation",
    board: "ICSE",
    classLevel: "11",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-icse-12",
    title: "Foundation Class 12 ICSE",
    description: "Foundation course for Class 12 ICSE students",
    longDescription: `A foundation course for Class 12 CBSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-cbse-10.jpg",
    targetExam: "Foundation",
    board: "CBSE",
    classLevel: "12",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-mh-11",
    title: "Foundation Class 11 MH Board",
    description: "Foundation course for Class 11 MH Board students",
    longDescription: `A foundation course for Class 10 CBSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-cbse-10.jpg",
    targetExam: "Foundation",
    board: "MH Board",
    classLevel: "11",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-mh-12",
    title: "Foundation Class 12 MH Board",
    description: "Foundation course for Class 12 CBSE students",
    longDescription: `A foundation course for Class 10 CBSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-mh-12.jpg",
    targetExam: "Foundation",
    board: "MH Board",
    classLevel: "12",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-icse-7",
    title: "Foundation Class 7 ICSE",
    description: "Foundation course for Class 7 ICSE students",
    longDescription: `A foundation course for Class 10 CBSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-icse-7.jpg",
    targetExam: "Foundation",
    board: "ICSE",
    classLevel: "7",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-mh-7",
    title: "Foundation Class 10 MH Board",
    description: "Foundation course for Class 7 MH Board students",
    longDescription: `A foundation course for Class 7 CBSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-mh-7.jpg",
    targetExam: "Foundation",
    board: "MH Board",
    classLevel: "7",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-icse-8",
    title: "Foundation Class 8 ICSE",
    description: "Foundation course for Class 8 ICSE students",
    longDescription: `A foundation course for Class 8 ICSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-icse-8.jpg",
    targetExam: "Foundation",
    board: "ICSE",
    classLevel: "8",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-icse-9",
    title: "Foundation Class 9 ICSE",
    description: "Foundation course for Class 9 ICSE students",
    longDescription: `A foundation course for Class 9 CBSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-icse-9.jpg",
    targetExam: "Foundation",
    board: "ICSE",
    classLevel: "9",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-mh-8",
    title: "Foundation Class 8 MH Board",
    description: "Foundation course for Class 10 CBSE students",
    longDescription: `A foundation course for Class 10 CBSE students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-mh-10.jpg",
    targetExam: "Foundation",
    board: "MH Board",
    classLevel: "8",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  {
    slug: "foundation-mh-9",
    title: "Foundation Class 9 MH Board",
    description: "Foundation course for Class 9 MH Board students",
    longDescription: `A foundation course for Class 9 MH Board students, focusing on concept clarity and exam preparation for board exams and future competitive exams.`,
    image: "/images/courses/foundation-mh-9.jpg",
    targetExam: "Foundation",
    board: "MH Board",
    classLevel: "9",
    price: "28,000/-",
    discountedPrice: "22,000/-",
  },
  // ...repeat for other foundation courses as needed
];
