import { Course } from "./types";

export const coursesData: Course[] = [
  {
    slug: "jee-dropper",
    title: "IIT JEE Dropper",
    description: "JEE dropper course for 12th pass students",
    longDescription: `This is a highly intensive course designed for JEE aspirants who have completed Class 12 and are targeting JEE Main and Advanced in the upcoming year. This batch offers rigorous practice, test series, personal mentoring and doubt sessions to boost your rank.`,
    image: "/course/iitdropper.png",
    targetExam: "JEE",
    programType: "Dropper",
  },
  {
    slug: "jee-one-year",
    title: "IIT JEE One Year",
    description: "One year course for JEE aspirants in Class 12",
    longDescription: `A focused one-year program for students moving to Class 12, targeting JEE Main and Advanced. Includes comprehensive study material, regular tests, and expert guidance.`,
    image: "/images/courses/jee-one-year.jpg",
    targetExam: "JEE",
    programType: "One Year",
   
  },
  {
    slug: "jee-two-year",
    title: "IIT JEE Two Year",
    description: "Two year course for JEE aspirants in Class 11",
    longDescription: `A two-year integrated program for students entering Class 11, covering the entire JEE syllabus with in-depth teaching, practice, and mentoring.`,
    image: "/images/courses/jee-two-year.jpg",
    targetExam: "JEE",
    programType: "Two Year",
    
  },
  {
    slug: "neet-dropper-batch",
    title: "NEET Dropper Batch",
    description: "NEET dropper course for 12th pass students",
    longDescription: `An intensive NEET preparation course for students who have completed Class 12. Includes exhaustive practice, test series, and doubt-solving sessions to maximize your NEET score.`,
    image: "/images/courses/neet-dropper.jpg",
    targetExam: "NEET",
    programType: "Dropper",
    
  },
  {
    slug: "neet-one-year",
    title: "NEET One Year",
    description: "One year course for NEET aspirants in Class 12",
    longDescription: `A one-year program for Class 12 students targeting NEET. Comprehensive coverage of Physics, Chemistry, and Biology with regular assessments and expert mentoring.`,
    image: "/images/courses/neet-one-year.jpg",
    targetExam: "NEET",
    programType: "One Year",
    
  },
  {
    slug: "neet-two-year",
    title: "NEET Two Year",
    description: "Two year course for NEET aspirants in Class 11",
    longDescription: `A two-year foundation course for students entering Class 11, focusing on building strong concepts and problem-solving skills for NEET.`,
    image: "/images/courses/neet-two-year.jpg",
    targetExam: "NEET",
    programType: "Two Year",
    
  },
  {
    slug: "cet-dropper",
    title: "CET Dropper",
    description: "CET dropper course for 12th pass students",
    longDescription: `A dedicated course for CET aspirants who have completed Class 12. Includes rigorous practice, mock tests, and personalized mentoring for best results.`,
    image: "/images/courses/cet-dropper.jpg",
    targetExam: "CET",
    programType: "Dropper",
    
  },
  {
    slug: "cet-one-year",
    title: "CET One Year",
    description: "One year course for CET aspirants in Class 12",
    longDescription: `A one-year program for Class 12 students preparing for CET. Covers all subjects with regular tests and expert guidance.`,
    image: "/images/courses/cet-one-year.jpg",
    targetExam: "CET",
    programType: "One Year",
   
  },
  {
    slug: "cet-two-year",
    title: "CET Two Year",
    description: "Two year course for CET aspirants in Class 11",
    longDescription: `A comprehensive two-year course for students entering Class 11, focusing on CET preparation with detailed study material and assessments.`,
    image: "/images/courses/cet-two-year.jpg",
    targetExam: "CET",
    programType: "Two Year",
    
  },
  {
    slug: "nda-dropper",
    title: "NDA Dropper",
    description: "NDA dropper course for 12th pass students",
    longDescription: `An intensive NDA preparation course for students who have completed Class 12. Includes focused study plans, test series, and personal mentoring.`,
    image: "/images/courses/nda-dropper.jpg",
    targetExam: "NDA",
    programType: "Dropper",
    
  },
  {
    slug: "nda-one-year",
    title: "NDA One Year",
    description: "One year course for NDA aspirants in Class 12",
    longDescription: `A one-year program for Class 12 students targeting NDA. Comprehensive coverage of all subjects, regular tests, and expert mentoring.`,
    image: "/images/courses/nda-one-year.jpg",
    targetExam: "NDA",
    programType: "One Year",
   
  },
  {
    slug: "nda-two-year",
    title: "NDA Two Year",
    description: "Two year course for NDA aspirants in Class 11",
    longDescription: `A two-year integrated program for students entering Class 11, focusing on NDA preparation with in-depth teaching and regular assessments.`,
    image: "/images/courses/nda-two-year.jpg",
    targetExam: "NDA",
    programType: "Two Year",
    
  },
  {
    slug: "foundation-cbse-7",
    title: "Foundation Class 7 CBSE",
    description: "Foundation course for Class 7 CBSE students",
    longDescription: `A foundation course for Class 7 CBSE students, focusing on building strong fundamentals in Science and Mathematics for future competitive exams.`,
    image: "/images/courses/foundation-cbse-7.jpg",
    targetExam: "Foundation",

    board: "CBSE",
    classLevel: "7",
  },
  {
    slug: "foundation-mh-7",
    title: "Foundation Class 7 MH Board",
    description: "Foundation course for Class 7 MH Board students",
    longDescription: `A foundation course for Class 7 MH Board students, focusing on building strong fundamentals in Science and Mathematics for future competitive exams.`,
    image: "/images/courses/foundation-mh-7.jpg",
    targetExam: "Foundation",

    board: "MH Board",
    classLevel: "7",
  },
  {
    slug: "foundation-icse-7",
    title: "Foundation Class 7 ICSE",
    description: "Foundation course for Class 7 ICSE students",
    longDescription: `A foundation course for Class 7 ICSE students, focusing on building strong fundamentals in Science and Mathematics for future competitive exams.`,
    image: "/images/courses/foundation-ICSE-7.jpg",
    targetExam: "Foundation",

    board: "ICSE",
    classLevel: "7",
  },
  {
    slug: "foundation-cbse-8",
    title: "Foundation Class 8 CBSE",
    description: "Foundation course for Class 8 CBSE students",
    longDescription: `A foundation course for Class 8 CBSE students, focusing on building strong fundamentals in Science and Mathematics for future competitive exams.`,
    image: "/images/courses/foundation-cbse-8.jpg",
    targetExam: "Foundation",

    board: "CBSE",
    classLevel: "8",
  },
  {
    slug: "foundation-cbse-9",
    title: "Foundation Class 9 CBSE",
    description: "Foundation course for Class 9 CBSE students",
    longDescription: `A foundation course for Class 9 CBSE students, strengthening concepts in Science and Mathematics and preparing for Olympiads and NTSE.`,
    image: "/images/courses/foundation-cbse-9.jpg",
    targetExam: "Foundation",
   
    board: "CBSE",
    classLevel: "9",
  },
  {
    slug: "foundation-cbse-10",
    title: "Foundation Class 10 CBSE",
    description: "Foundation course for Class 10 CBSE students",
    longDescription: `A foundation course for Class 10 CBSE students, focusing on board exam preparation and building a base for competitive exams like JEE/NEET.`,
    image: "/images/courses/foundation-cbse-10.jpg",
    targetExam: "Foundation",
   
    board: "CBSE",
    classLevel: "10",
  },
  {
    slug: "foundation-cbse-11",
    title: "Foundation Class 11 CBSE",
    description: "Foundation course for Class 11 CBSE students",
    longDescription: `A foundation course for Class 11 CBSE students, focusing on advanced concepts and preparing for competitive exams.`,
    image: "/images/courses/foundation-cbse-11.jpg",
    targetExam: "Foundation",
  
    board: "CBSE",
    classLevel: "11",
  },
  {
    slug: "foundation-cbse-12",
    title: "Foundation Class 12 CBSE",
    description: "Foundation course for Class 12 CBSE students",
    longDescription: `A foundation course for Class 12 CBSE students, focusing on board exam excellence and competitive exam readiness.`,
    image: "/images/courses/foundation-cbse-12.jpg",
    targetExam: "Foundation",
   
    board: "CBSE",
    classLevel: "12",
  },
  {
    slug: "foundation-icse-8",
    title: "Foundation Class 8 ICSE",
    description: "Foundation course for Class 8 ICSE students",
    longDescription: `A foundation course for Class 8 ICSE students, building strong fundamentals in Science and Mathematics for future success.`,
    image: "/images/courses/foundation-icse-8.jpg",
    targetExam: "Foundation",
    
    board: "ICSE",
    classLevel: "8",
  },
  {
    slug: "foundation-icse-9",
    title: "Foundation Class 9 ICSE",
    description: "Foundation course for Class 9 ICSE students",
    longDescription: `A foundation course for Class 9 ICSE students, strengthening concepts and preparing for Olympiads and NTSE.`,
    image: "/images/courses/foundation-icse-9.jpg",
    targetExam: "Foundation",
    
    board: "ICSE",
    classLevel: "9",
  },
  {
    slug: "foundation-icse-10",
    title: "Foundation Class 10 ICSE",
    description: "Foundation course for Class 10 ICSE students",
    longDescription: `A foundation course for Class 10 ICSE students, focusing on board exam preparation and competitive exam foundation.`,
    image: "/images/courses/foundation-icse-10.jpg",
    targetExam: "Foundation",
   
    board: "ICSE",
    classLevel: "10",
  },
  {
    slug: "foundation-icse-11",
    title: "Foundation Class 11 ICSE",
    description: "Foundation course for Class 11 ICSE students",
    longDescription: `A foundation course for Class 11 ICSE students, focusing on advanced concepts and competitive exam readiness.`,
    image: "/images/courses/foundation-icse-11.jpg",
    targetExam: "Foundation",
    
    board: "ICSE",
    classLevel: "11",
  },
  {
    slug: "foundation-icse-12",
    title: "Foundation Class 12 ICSE",
    description: "Foundation course for Class 12 ICSE students",
    longDescription: `A foundation course for Class 12 ICSE students, focusing on board exam excellence and competitive exam preparation.`,
    image: "/images/courses/foundation-icse-12.jpg",
    targetExam: "Foundation",
    
    board: "ICSE",
    classLevel: "12",
  },
  {
    slug: "foundation-mh-8",
    title: "Foundation Class 8 MH",
    description: "Foundation course for Class 8 Maharashtra Board students",
    longDescription: `A foundation course for Class 8 Maharashtra Board students, building strong fundamentals in Science and Mathematics.`,
    image: "/images/courses/foundation-mh-8.jpg",
    targetExam: "Foundation",
    
    board: "MH Board",
    classLevel: "8",
  },
  {
    slug: "foundation-mh-9",
    title: "Foundation Class 9 MH",
    description: "Foundation course for Class 9 Maharashtra Board students",
    longDescription: `A foundation course for Class 9 Maharashtra Board students, strengthening concepts and preparing for Olympiads and NTSE.`,
    image: "/images/courses/foundation-mh-9.jpg",
    targetExam: "Foundation",
    
    board: "MH Board",
    classLevel: "9",
  },
  {
    slug: "foundation-mh-10",
    title: "Foundation Class 10 MH",
    description: "Foundation course for Class 10 Maharashtra Board students",
    longDescription: `A foundation course for Class 10 Maharashtra Board students, focusing on board exam preparation and competitive exam foundation.`,
    image: "/images/courses/foundation-mh-10.jpg",
    targetExam: "Foundation",
    
    board: "MH Board",
    classLevel: "10",
  },
  {
    slug: "foundation-mh-11",
    title: "Foundation Class 11 MH",
    description: "Foundation course for Class 11 Maharashtra Board students",
    longDescription: `A foundation course for Class 11 Maharashtra Board students, focusing on advanced concepts and competitive exam readiness.`,
    image: "/images/courses/foundation-mh-11.jpg",
    targetExam: "Foundation",
    
    board: "MH Board",
    classLevel: "11",
  },
  {
    slug: "foundation-mh-12",
    title: "Foundation Class 12 MH",
    description: "Foundation course for Class 12 Maharashtra Board students",
    longDescription: `A foundation course for Class 12 Maharashtra Board students, focusing on board exam excellence and competitive exam preparation.`,
    image: "/images/courses/foundation-mh-12.jpg",
    targetExam: "Foundation",
    
    board: "MH Board",
    classLevel: "12",
  },
];
