export const studentResults = [
  {
    id: 1,
    name: "Mohd. Amaan",
    result: "CET - 475/500",
    rank: "MIT Kothrud",
    image: "/results/student2.png",
  },
  {
    id: 2,
    name: "Amit Sangwan",
    result: "",
    rank: "Walchand COE , Sangli",
    image: "/results/student3.png",
  },
  {
    id: 3,
    name: "Anisha Chishti",
    result: "CET - 447/500",
    rank: "MBBS - Bangladesh",
    image: "/results/student4.png",
  },
  {
    id: 4,
    name: "Ankit Sangwan",
    result: "450/500",
    rank: "AIT, Pune",
    image: "/results/student5.png",
  },
  {
    id: 5,
    name: "Anshika Chauhan",
    result: "CBSE 10th",
    rank: "476/500 ",
    image: "/results/student6.png",
  },
  {
    id: 6,
    name: "Aparna Shinde",
    result: "NEET 650/720",
    rank: "Govt. Medical College, Nanded",
    image: "/results/student7.png",
  },
  {
    id: 7,
    name: "Ardra Thakare",
    result: "451/500",
    rank: "VJIT Mumbai, CSE",
    image: "/results/student8.png",
  },
  {
    id: 8,
    name: "Aashna Siddiqui",
    result: "CET - 460/500",
    rank: "PCMB - 92%",
    image: "/results/student9.png",
  },
  {
    id: 9,
    name: "Atharva Pachure",
    result: "",
    rank: "JEE Mains- 95%ile",
    image: "/results/student10.png",
  },
  {
    id: 10,
    name: "Ayesha Khalife",
    result: "464/500",
    rank: "Govt. College, Ratnagiri",
    image: "/results/student11.png",
  },
    {
      id: 11,
      name: "Karan Suryavanshi",
      result: "456/500",
      rank: "VJIT, Mumbai",
      image: "/results/student12.png",
    },
    {
      id: 12,
      name: "Karthik Bankar",
      result: "488/500",
      rank: "JEE Mains - 96.5%ile",
      image: "/results/student13.png",
    },
    {
      id: 12,
      name: "Khushboo Kumar",
      result: "MBBS",
      rank: "National Institute of Medical Sciences, Delhi",
      image: "/results/student14.png",
    },
    {
      id: 12,
      name: "Numa Sheikh",
      result: "490/500",
      rank: "Manipal University",
      image: "/results/student15.png",
    },
    {
      id: 12,
      name: "Piyush Nindane",
      result: "520/600",
      rank: "COEP, Pune - CSE",
      image: "/results/student16.png",
    },
    {
      id: 12,
      name: "Prerna Mali",
      result: "",
      rank: "BDS Pune",
      image: "/results/student17.png",
    },
    {
      id: 12,
      name: "Hridaya Prasantha",
      result: "490/500",
      rank: "MIT, Pune - CSE",
      image: "/results/student18.png",
    },
    {
      id: 12,
      name: "Rizwan Parveen",
      result: "MBBS - 460/500",
      rank: "Govt. College - West Bengal",
      image: "/results/student19.png",
    },
    
    {
      id: 12,
      name: "Sandesh Lad",
      result: "",
      rank: "10th 489/500",
      image: "/results/student20.png",
    },
    
    {
      id: 12,
      name: "Saurab Saini",
      result: "JEE Mains - 488/500",
      rank: "IIT Jammu - CSE",
      image: "/results/student21.png",
    },
    
    {
      id: 12,
      name: "Siddharth Tribhuvan",
      result: "",
      rank: "COEP, Pune",
      image: "/results/student22.png",
    },
    
    {
      id: 12,
      name: "Surjeet Gosh",
      result: "Army Public School, Pune",
      rank: "PCMB - 94.4%",
      image: "/results/student23.png",
    },
    
    {
      id: 12,
      name: "Tabish Ansari",
      result: "12th 480/500",
      rank: "AISSMS, Pune",
      image: "/results/student24.png",
    },
    
    {
      id: 12,
      name: "Vaishnavi Firode",
      result: "BDS",
      rank: "Bharti Vidyapeeth, Pune",
      image: "/results/student25.png",
    },
    
    {
      id: 12,
      name: "Vinay Ingle",
      result: "470/500",
      rank: "IIT Palakad - CSE",
      image: "/results/student26.png",
    },
    
];
