export const studentResults = [
  {
    id: 1,
    name: "Aritro Ray",
    result: "IIT Bombay",
    rank: "JEE Adv. AIR 50",
    image: "/results/student1.png",
  },
  {
    id: 2,
    name: "Arka Banerjee",
    result: "IIT Kharagpur",
    rank: "JEE Adv. AIR 395",
    image: "/results/student1.png",
  },
  {
    id: 3,
    name: "Chirag Singh",
    result: "AIIMS Delhi",
    rank: "AIIMS - AIR 51",
    image: "/results/student1.png",
  },
  {
    id: 4,
    name: "Aryan Mishra",
    result: "District Topper",
    rank: "10th Board - 98.5%",
    image: "/results/student1.png",
  },
  {
    id: 5,
    name: "Azim Ahmed",
    result: "West Bengal",
    rank: "JEE Adv. AIR 50",
    image: "/results/student1.png",
  },
  {
    id: 6,
    name: "Nishchay Kapoor",
    result: "Haryana",
    rank: "12th Board - 98.5%",
    image: "/results/student1.png",
  },
  {
    id: 7,
    name: "Praneel Pathak",
    result: "Haryana",
    rank: "NEET - 690/720",
    image: "/results/student1.png",
  },
  {
    id: 8,
    name: "Soham Pandit",
    result: "West Bengal",
    rank: "NDA - AIR 1200",
    image: "/results/student1.png",
  },
  {
    id: 9,
    name: "Param V. Patel",
    result: "Gujarat",
    rank: "MHTCET. AIR 1500",
    image: "/results/student1.png",
  },
  {
    id: 10,
    name: "Subhanjan Parai",
    result: "West Bengal",
    rank: "IIT Adv. AIR 2000",
    image: "/results/student1.png",
  },
  //   {
  //     id: 11,
  //     name: "Veeram N. Shah",
  //     result: "Maharashtra",
  //     rank: "AIR 2600",
  //     image: "/students/student11.jpg",
  //   },
  //   {
  //     id: 12,
  //     name: "Mayank V. Ojha",
  //     result: "Maharashtra",
  //     rank: "AIR 3030",
  //     image: "/students/student12.jpg",
  //   },
  //   {
  //     id: 13,
  //     name: "Vishesh Agrawal",
  //     result: "Odisha",
  //     rank: "AIR 3131",
  //     image: "/students/student13.jpg",
  //   },
  //   {
  //     id: 14,
  //     name: "Akash Gupta",
  //     result: "Madhya Pradesh",
  //     rank: "AIR 3196",
  //     image: "/students/student14.jpg",
  //   },
  //   {
  //     id: 15,
  //     name: "Harsh Rawat",
  //     result: "Madhya Pradesh",
  //     rank: "AIR 3348",
  //     image: "/students/student15.jpg",
  //   },
  //   {
  //     id: 16,
  //     name: "Dev Jaiswal",
  //     result: "Uttar Pradesh",
  //     rank: "AIR 3385",
  //     image: "/students/student16.jpg",
  //   },
  //   {
  //     id: 17,
  //     name: "Ahmad Shayan",
  //     result: "West Bengal",
  //     rank: "AIR 3680",
  //     image: "/students/student17.jpg",
  //   },
  //   {
  //     id: 18,
  //     name: "Shaurya Agarwal",
  //     result: "Uttar Pradesh",
  //     rank: "AIR 5186",
  //     image: "/students/student18.jpg",
  //   },
  //   {
  //     id: 19,
  //     name: "Anubhav Dubey",
  //     result: "Madhya Pradesh",
  //     rank: "AIR 5309",
  //     image: "/students/student19.jpg",
  //   },
  //   {
  //     id: 20,
  //     name: "Vedant Dikshit",
  //     result: "Uttar Pradesh",
  //     rank: "AIR 8728",
  //     image: "/students/student20.jpg",
  //   },
];
